### ISSUE TITLE
Mass always is 0

### ISSUE THREAD

**Issue by ManiRX100** [mcanet/STL-Volume-Model-Calculator#12]
Hi
I tried using this code with several STL files. I always end up with "Total mass could not be calculated" even though the volume is calculated correctly. What am i missing here? I checked with different unit systems also.

**Comment by costia** [comment]
It's the material type check.
"if material in {1, 'ABS'}" and all the other ones expect an integer, but you get the number as a string from the input.
So you get '1' instead of 1.
Need to either convert the input to integer or change the checks to strings.
This results in the volume to mass conversion to silently fail and return a mass of 0.
